name: gitHub Actions 실행하기2
on:
  push:
    branches:
      -main

jobs:
  My-Deploy-job:
    runs-on: ubuntu-latest

    steps:
      - name: Hellow World 찍기
        run: echo "Hellow World"

    steps:
      - name: Hellow World 찍기2
        run: |
          echo "Hood"
          echo "Hii"

